service_uuids = [{'identifier': 'org.bluetooth.service.generic_access',
  'name': 'Generic Access',
  'source': 'gss',
  'uuid': '1800'},
 {'identifier': 'org.bluetooth.service.alert_notification',
  'name': 'Alert Notification Service',
  'source': 'gss',
  'uuid': '1811'},
 {'identifier': 'org.bluetooth.service.automation_io',
  'name': 'Automation IO',
  'source': 'gss',
  'uuid': '1815'},
 {'identifier': 'org.bluetooth.service.battery_service',
  'name': 'Battery Service',
  'source': 'gss',
  'uuid': '180F'},
 {'identifier': 'org.bluetooth.service.blood_pressure',
  'name': 'Blood Pressure',
  'source': 'gss',
  'uuid': '1810'},
 {'identifier': 'org.bluetooth.service.body_composition',
  'name': 'Body Composition',
  'source': 'gss',
  'uuid': '181B'},
 {'identifier': 'org.bluetooth.service.bond_management',
  'name': 'Bond Management Service',
  'source': 'gss',
  'uuid': '181E'},
 {'identifier': 'org.bluetooth.service.continuous_glucose_monitoring',
  'name': 'Continuous Glucose Monitoring',
  'source': 'gss',
  'uuid': '181F'},
 {'identifier': 'org.bluetooth.service.current_time',
  'name': 'Current Time Service',
  'source': 'gss',
  'uuid': '1805'},
 {'identifier': 'org.bluetooth.service.cycling_power',
  'name': 'Cycling Power',
  'source': 'gss',
  'uuid': '1818'},
 {'identifier': 'org.bluetooth.service.cycling_speed_and_cadence',
  'name': 'Cycling Speed and Cadence',
  'source': 'gss',
  'uuid': '1816'},
 {'identifier': 'org.bluetooth.service.device_information',
  'name': 'Device Information',
  'source': 'gss',
  'uuid': '180A'},
 {'identifier': 'org.bluetooth.service.environmental_sensing',
  'name': 'Environmental Sensing',
  'source': 'gss',
  'uuid': '181A'},
 {'identifier': 'org.bluetooth.service.fitness_machine',
  'name': 'Fitness Machine',
  'source': 'gss',
  'uuid': '1826'},
 {'identifier': 'org.bluetooth.service.generic_attribute',
  'name': 'Generic Attribute',
  'source': 'gss',
  'uuid': '1801'},
 {'identifier': 'org.bluetooth.service.glucose',
  'name': 'Glucose',
  'source': 'gss',
  'uuid': '1808'},
 {'identifier': 'org.bluetooth.service.health_thermometer',
  'name': 'Health Thermometer',
  'source': 'gss',
  'uuid': '1809'},
 {'identifier': 'org.bluetooth.service.heart_rate',
  'name': 'Heart Rate',
  'source': 'gss',
  'uuid': '180D'},
 {'identifier': 'org.bluetooth.service.http_proxy',
  'name': 'HTTP Proxy',
  'source': 'gss',
  'uuid': '1823'},
 {'identifier': 'org.bluetooth.service.human_interface_device',
  'name': 'Human Interface Device',
  'source': 'gss',
  'uuid': '1812'},
 {'identifier': 'org.bluetooth.service.immediate_alert',
  'name': 'Immediate Alert',
  'source': 'gss',
  'uuid': '1802'},
 {'identifier': 'org.bluetooth.service.indoor_positioning',
  'name': 'Indoor Positioning',
  'source': 'gss',
  'uuid': '1821'},
 {'identifier': 'org.bluetooth.service.insulin_delivery',
  'name': 'Insulin Delivery',
  'source': 'gss',
  'uuid': '183A'},
 {'identifier': 'org.bluetooth.service.internet_protocol_support',
  'name': 'Internet Protocol Support Service',
  'source': 'gss',
  'uuid': '1820'},
 {'identifier': 'org.bluetooth.service.link_loss',
  'name': 'Link Loss',
  'source': 'gss',
  'uuid': '1803'},
 {'identifier': 'org.bluetooth.service.location_and_navigation',
  'name': 'Location and Navigation',
  'source': 'gss',
  'uuid': '1819'},
 {'identifier': 'org.bluetooth.service.mesh_provisioning',
  'name': 'Mesh Provisioning Service',
  'source': 'gss',
  'uuid': '1827'},
 {'identifier': ' org.bluetooth.service.mesh_proxy',
  'name': 'Mesh Proxy Service',
  'source': 'gss',
  'uuid': '1828'},
 {'identifier': 'org.bluetooth.service.next_dst_change',
  'name': 'Next DST Change Service',
  'source': 'gss',
  'uuid': '1807'},
 {'identifier': 'org.bluetooth.service.object_transfer',
  'name': 'Object Transfer Service',
  'source': 'gss',
  'uuid': '1825'},
 {'identifier': 'org.bluetooth.service.phone_alert_status',
  'name': 'Phone Alert Status Service',
  'source': 'gss',
  'uuid': '180E'},
 {'identifier': 'org.bluetooth.service.pulse_oximeter',
  'name': 'Pulse Oximeter Service',
  'source': 'gss',
  'uuid': '1822'},
 {'identifier': 'org.bluetooth.service.reconnection_configuration',
  'name': 'Reconnection Configuration',
  'source': 'gss',
  'uuid': '1829'},
 {'identifier': 'org.bluetooth.service.reference_time_update',
  'name': 'Reference Time Update Service',
  'source': 'gss',
  'uuid': '1806'},
 {'identifier': 'org.bluetooth.service.running_speed_and_cadence',
  'name': 'Running Speed and Cadence',
  'source': 'gss',
  'uuid': '1814'},
 {'identifier': 'org.bluetooth.service.scan_parameters',
  'name': 'Scan Parameters',
  'source': 'gss',
  'uuid': '1813'},
 {'identifier': 'org.bluetooth.service.transport_discovery',
  'name': 'Transport Discovery',
  'source': 'gss',
  'uuid': '1824'},
 {'identifier': 'org.bluetooth.service.tx_power',
  'name': 'Tx Power',
  'source': 'gss',
  'uuid': '1804'},
 {'identifier': 'org.bluetooth.service.user_data',
  'name': 'User Data',
  'source': 'gss',
  'uuid': '181C'},
 {'identifier': 'org.bluetooth.service.weight_scale',
  'name': 'Weight Scale',
  'source': 'gss',
  'uuid': '181D'}]