"""Change Rides.active default to True

Revision ID: 4c4855dde9f5
Revises: 26d4d39210ff
Create Date: 2022-01-20 20:59:50.129615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4855dde9f5'
down_revision = '26d4d39210ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
