"""Add settings table

Revision ID: c7dd6d36b41e
Revises: 68968c14ecde
Create Date: 2022-11-02 08:46:15.446878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7dd6d36b41e'
down_revision = '68968c14ecde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lcd_brightness', sa.Integer(), nullable=True),
    sa.Column('wifi_enabled', sa.Boolean(), nullable=True),
    sa.Column('bluetooth_enabled', sa.Boolean(), nullable=True),
    sa.Column('lights_enabled', sa.Boolean(), nullable=True),
    sa.Column('upload_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
